### ISSUE TITLE
Implementing MGTwitterEngine on iPad

### ISSUE THREAD

**Issue by hakimny** [mattgemmell/MGTwitterEngine#68]
Hi guys

I am getting this link erro when i try to compile on iPad OS 3.2

" Undefined symbols:
  "_dispatch_get_main_queue", referenced from:
      ___-[CJSONDeserializer(CJSONDeserializer_BlocksExtensions) deserializeAsDictionary:completionBlock:]_block_invoke_1 in CJSONDeserializer_BlocksExtensions.o
      ___-[CJSONDeserializer(CJSONDeserializer_BlocksExtensions) deserializeAsArray:completionBlock:]_block_invoke_1 in CJSONDeserializer_BlocksExtensions.o
ld: symbol(s) not found
collect2: ld returned 1 exit status "

"Undefined symbols:
  "_dispatch_get_main_queue", referenced from:
      ___-[CJSONDeserializer(CJSONDeserializer_BlocksExtensions) deserializeAsDictionary:completionBlock:]_block_invoke_1 in CJSONDeserializer_BlocksExtensions.o
      ___-[CJSONDeserializer(CJSONDeserializer_BlocksExtensions) deserializeAsArray:completionBlock:]_block_invoke_1 in CJSONDeserializer_BlocksExtensions.o
ld: symbol(s) not found
collect2: ld returned 1 exit status"

any help on how to fix this is highly appreciated

Thx to all

**Comment by catsby** [comment]
I believe you're using blocks or Grand Central Dispatch, and I don't think iPad SDK 3.2 supports those.  Grand Central, for instance, was added with iOS 4.

**Comment by hakimny** [comment]
Thx I will try to run a TESt with iOS 4.2 and see what's teh outcome

Thx for your answer
