### ISSUE TITLE
Cannot Compile on XCode 4 with libxml

### ISSUE THREAD

**Issue by moyitpro** [mattgemmell/MGTwitterEngine#77]
Won't compile with XCode 4 as it calls an error that libxml does not exist. 

/Users/ashe/Documents/malupdaterosx-cocoa/Twitter/MGTwitterLibXMLParser.h:10:30: error: libxml/xmlreader.h: No such file or directory

/Users/ashe/Documents/malupdaterosx-cocoa/Twitter/MGTwitterLibXMLParser.h:10:30: error: libxml/xmlreader.h: No such file or directory

**Comment by bliang** [comment]
I don't think this is an issue with XCode 4, ensure that you have the search headers pointing to the correct path.

**Comment by moyitpro** [comment]
I used "${SDKROOT}/usr/include/libxml2" and check recursive and it brings up this error. This error does not show when you compile in XCode 3.2.

**Comment by bnk** [comment]
Go to your Build Settings, in GCC 4.2 - Code Generation change the value from "Fastest, Smallest [-Os]" to another. Then go back to "Fastest, Smallest [-Os]". I have no explanations but it works now.

**Comment by moyitpro** [comment]
Problems fixed. Thanks for the suggestion.

**Comment by sascsedu** [comment]
@bnk:

I have tried with your solution. The value "Fastest, Smallest [-Os]" , I get this only in the Optimazation level ..... right??

However i tried by changing this value. But this doesn't worked for me. Any more suggestion please..

**Comment by bnk** [comment]
@sascsedu

Unfortunately, I don't have other suggestions.

Make sure your search headers are pointing to the correct path.
Then change the value clean your project (command+shit+k), build it then go back to "Fastest, Smallest [-Os]".

**Comment by FreeApple** [comment]
In your header path change from "any architecture" to  "ARMv6 architecture"
